### ISSUE TITLE
d1to2fix segfaults with many arguments

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/d1to2fix#24]
```
nemanjaboric@labs-129:/home/nemanjaboric/tmp/d1fixbug  git:(config-scripts*) $ ls
emptydir  files.txt  test.d
nemanjaboric@labs-129:/home/nemanjaboric/tmp/d1fixbug  git:(config-scripts*) $ ls emptydir 
nemanjaboric@labs-129:/home/nemanjaboric/tmp/d1fixbug  git:(config-scripts*) $ cat test.d
void main() {}
nemanjaboric@labs-129:/home/nemanjaboric/tmp/d1fixbug  git:(config-scripts*) $ cat files.txt
test.d
```

Now, run:

```
nemanjaboric@labs-129:/home/nemanjaboric/tmp/d1fixbug  git:(config-scripts*) $ d1to2fix -Iemptydir -Iemptydir -Iemptydir --fatal --input=files.txt
[1]    16700 segmentation fault  d1to2fix -Iemptydir -Iemptydir -Iemptydir --fatal --input=files.txt
```

```

Thread 1 "d1to2fix" received signal SIGSEGV, Segmentation fault.
0x0000000000850ea3 in dsymbol.symbol.DSymbol.__aggrDtor() (this=...) at ./submodules/emsi_containers/src/containers/ttree.d:174
174	./submodules/emsi_containers/src/containers/ttree.d: No such file or directory.
(gdb) bt
#0  0x0000000000850ea3 in dsymbol.symbol.DSymbol.__aggrDtor() (this=...) at ./submodules/emsi_containers/src/containers/ttree.d:174
#1  0x000000000076208a in object.destroy!(dsymbol.cache_entry.CacheEntry).destroy(ref dsymbol.cache_entry.CacheEntry) (obj=...) at /usr/include/dmd/druntime/import/object.d:1181
#2  0x00000000008c788a in dsymbol.modulecache.ModuleCache.__aggrDtor() (this=...) at ./submodules/experimental_allocator/src/std/experimental/allocator/package.d:1057
#3  0x00000000009505fe in rt.lifetime.finalize_struct(void*, ulong) ()
#4  0x0000000000940067 in rt_finalizeFromGC ()
#5  0x000000000093abaf in gc.gc.Gcx.sweep() ()
#6  0x000000000093b491 in gc.gc.Gcx.fullcollect(bool) ()
#7  0x000000000093db39 in gc.gc.GC.runLocked!(gc.gc.GC.fullCollectNoStack().go(gc.gc.Gcx*), gc.gc.Gcx*).runLocked(ref gc.gc.Gcx*) ()
#8  0x0000000000937d29 in gc.gc.GC.fullCollectNoStack() ()
#9  0x000000000094fe32 in gc_term ()
#10 0x000000000093f260 in rt_term ()
#11 0x00000000009014e5 in rt.dmain2._d_run_main(int, char**, extern(C) int(char[][]) function).runAll() ()
#12 0x0000000000901465 in rt.dmain2._d_run_main(int, char**, extern(C) int(char[][]) function).tryExec(scope void() delegate) ()
#13 0x00000000009013d6 in _d_run_main ()
#14 0x00000000007648d6 in main ()
#15 0x00007ffff73f2830 in __libc_start_main (main=0x7648c8 <main>, argc=6, argv=0x7fffffffdf08, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdef8)
    at ../csu/libc-start.c:291
#16 0x000000000074fab9 in _start ()
```

It looks like even different arguments can trip it, for example, this behaves the same:

```
d1to2fix -Iemptydir -Iemptydir -Iemptydir -Iemptydir -Iemptydir test.d
```

```
(gdb) bt
#0  0x0000000000850ea3 in dsymbol.symbol.DSymbol.__aggrDtor() (this=...) at ./submodules/emsi_containers/src/containers/ttree.d:174
#1  0x000000000076208a in object.destroy!(dsymbol.cache_entry.CacheEntry).destroy(ref dsymbol.cache_entry.CacheEntry) (obj=...) at /usr/include/dmd/druntime/import/object.d:1181
#2  0x00000000008c788a in dsymbol.modulecache.ModuleCache.__aggrDtor() (this=...) at ./submodules/experimental_allocator/src/std/experimental/allocator/package.d:1057
#3  0x00000000009505fe in rt.lifetime.finalize_struct(void*, ulong) ()
#4  0x0000000000940067 in rt_finalizeFromGC ()
#5  0x000000000093abaf in gc.gc.Gcx.sweep() ()
#6  0x000000000093b491 in gc.gc.Gcx.fullcollect(bool) ()
#7  0x000000000093db39 in gc.gc.GC.runLocked!(gc.gc.GC.fullCollectNoStack().go(gc.gc.Gcx*), gc.gc.Gcx*).runLocked(ref gc.gc.Gcx*) ()
#8  0x0000000000937d29 in gc.gc.GC.fullCollectNoStack() ()
#9  0x000000000094fe32 in gc_term ()
#10 0x000000000093f260 in rt_term ()
#11 0x00000000009014e5 in rt.dmain2._d_run_main(int, char**, extern(C) int(char[][]) function).runAll() ()
#12 0x0000000000901465 in rt.dmain2._d_run_main(int, char**, extern(C) int(char[][]) function).tryExec(scope void() delegate) ()
#13 0x00000000009013d6 in _d_run_main ()
#14 0x00000000007648d6 in main ()
#15 0x00007ffff73f2830 in __libc_start_main (main=0x7648c8 <main>, argc=7, argv=0x7fffffffdf08, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdef8)
    at ../csu/libc-start.c:291
#16 0x000000000074fab9 in _start ()
```

**Comment by nemanja-boric-sociomantic** [comment]
Tested with 0.9.0+5~d0e3c38-xenial and 0.10.0-alpha1-xenial

**Comment by mathias-lang-sociomantic** [comment]
Setting prio-high since it prevent some apps from upgrading to a newer MakD
